server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 111111
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  application:
    name: httpsdemo1
  redis:
    host: 127.0.0.1
    timeout: 3000
    password:
    port: 6379
    database: 0

